import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'The Mayfair Suit',
    description: 'A timeless navy blue suit crafted from 100% merino wool. Perfect for business or formal occasions.',
    price: 799.99,
    category: 'Suits',
    imageId: 'suit1',
  },
  {
    id: 'prod_002',
    name: 'The City Slicker Suit',
    description: 'A modern slim-fit suit in charcoal grey. Its versatile shade makes it a wardrobe staple.',
    price: 649.99,
    category: 'Suits',
    imageId: 'suit2',
  },
  {
    id: 'prod_003',
    name: 'The Executive Shirt',
    description: 'A crisp, non-iron dress shirt in pure white cotton with a classic spread collar.',
    price: 89.99,
    category: 'Shirts',
    imageId: 'shirt1',
  },
  {
    id: 'prod_004',
    name: 'The Weekend Oxford',
    description: 'A comfortable yet sharp button-down shirt in light blue oxford cloth.',
    price: 79.99,
    category: 'Shirts',
    imageId: 'shirt2',
  },
  {
    id: 'prod_005',
    name: 'The Chairman Oxfords',
    description: 'Hand-polished black calfskin leather oxfords. The epitome of formal footwear.',
    price: 349.99,
    category: 'Shoes',
    imageId: 'shoes1',
  },
  {
    id: 'prod_006',
    name: 'The Ambassador Brogues',
    description: 'Rich brown leather brogues with detailed perforations. Perfect for smart-casual.',
    price: 329.99,
    category: 'Shoes',
    imageId: 'shoes2',
  },
  {
    id: 'prod_007',
    name: 'The Statesman Tie',
    description: 'A luxurious silk tie in a deep burgundy, adding a touch of class to any outfit.',
    price: 59.99,
    category: 'Accessories',
    imageId: 'tie1',
  },
  {
    id: 'prod_008',
    name: 'The Chronograph',
    description: 'A sophisticated timepiece with a stainless steel case and a genuine leather strap.',
    price: 499.99,
    category: 'Accessories',
    imageId: 'watch1',
  },
  {
    id: 'prod_009',
    name: 'The Diplomat Briefcase',
    description: 'A full-grain leather briefcase with a timeless design, for the professional on the move.',
    price: 450.00,
    category: 'Accessories',
    imageId: 'briefcase1',
  },
  {
    id: 'prod_010',
    name: 'The Gatsby Suit',
    description: 'A bold double-breasted pinstripe suit that makes a statement.',
    price: 899.99,
    category: 'Suits',
    imageId: 'suit3',
  },
  {
    id: 'prod_011',
    name: 'The Riviera Loafers',
    description: 'Comfortable and stylish suede loafers in a versatile sand color.',
    price: 289.99,
    category: 'Shoes',
    imageId: 'shoes3',
  }
];
