// @ts-nocheck
// This file is autogenerated by Firebase Studio. Do not edit.

// Your web app's Firebase configuration
export const firebaseConfig = {
  apiKey: "AIzaSyDYfKA6hjXOjh1eUDxGOIu02FmcQHBnGjM",
  authDomain: "studio-5281008203-fcbd7.firebaseapp.com",
  projectId: "studio-5281008203-fcbd7",
  storageBucket: "studio-5281008203-fcbd7.appspot.com",
  messagingSenderId: "631166947523",
  appId: "1:631166947523:web:c73ed630e9c9cc3e681276"
};
